### ISSUE TITLE
Police not getting text

### ISSUE THREAD

**Issue by daffiestfrog41** [HalCroves/gcphone#10]
Hello, I have just installed your version of gcphone on a server and everything works great except for some reason when someone texts the police, nobody who has the policejob gets it but a random person gets the text that is meant for the police. Was wondering if anyone has any insight on why this may be?

**Comment by HalCroves** [comment]
Hi.
Which addon do you use ? esx_policejob ?

**Comment by daffiestfrog41** [comment]
@HalCroves Sorry, I use the latest esx_policejob

**Comment by HalCroves** [comment]
Hi,
Do you have any logs in your console when you texts the police ? When you call the police number, it works ?
