### ISSUE TITLE
Demande

### ISSUE THREAD

**Issue by CubeTroy** [HalCroves/gcphone#12]
Salut, je sais pas si tu te souviens de moi, je voulais te demandé si cette dernière version marche a 100% ?

**Comment by HalCroves** [comment]
Salut, 
Logiquement oui. :)

**Comment by CubeTroy** [comment]
Salut,
Et il y à pas moyen de faire quelque choses pour qu'ont entends les personne qui sont au téléphone ?
Merci

**Comment by HalCroves** [comment]
o7
Plusieurs choses: 
Soit passé par un serveur WebRTC
Soit passé par https://github.com/PichotM/VoiceChat

**Comment by CubeTroy** [comment]
Tu peux pas le faire directement ?

**Comment by HalCroves** [comment]
Configure the voice, in gcphone/html/static/config/config.json.
Basic use "useWebRTCVocal": false, unless you have a custom RTC server.
