### ISSUE TITLE
Whitescreen

### ISSUE THREAD

**Issue by CubeTroy** [HalCroves/gcphone#2]
Hey !
Je vois que t'es en plein dev, t'aurais pas une idée du problème du whitescreen dans les messages que certaine personne ont ?!
Si tu peux me contacter discord : CubeTroy#7033

**Comment by CubeTroy** [comment]
Ah avec la nouvelle update maintenant des que tu envoyé un message tu ne le vois pas etl e téléphone reste ouvert et freeze

**Comment by HalCroves** [comment]
Hello,
Pour l'update, je regarde dès que possible (surement partir en rollback).
- Rollback fait

Pour ce qui est du whitescreen, je ne sais pas réellement d'ou provient cette anomalie.

**Piste :** 
- Problème avec mysql (données qui ont du mal à remonter)
   - Au niveau de la version, la version qui fonctionne est la 2.x https://github.com/brouznouf/fivem-mysql-async/tree/2.0
- Problème de refresh du téléphone
- Cache du serveur
- Le placement du `start gcphone` et `start esx_addons_gcphone`

**Comment by CubeTroy** [comment]
Bonjour,
Après avoir mis la version mysql que vous avez envoyez, plus aucun bug plus de whitescreen, plus de bug de rafraîchissement !
Merci beaucoup pour le travaille que vous faites

**Comment by HalCroves** [comment]
Nice,

Ce n'est pas mon travail, je l'ai juste repris pour des besoins personnelles et pour partager ce qu'il "manquer" :+1: 

Peux-tu me donner quelques informations du coup ?
- Ton serveur tourne sous Windows ou Linux ?
- Quelle version de mysql-async avez-tu ?

Cdt.

**Comment by CubeTroy** [comment]
Bien-sûr !
• Mon serveur et sous VPS Linux ! 
• J'avais la 3.0.8 celle de base que tu trouves sur github https://github.com/brouznouf/fivem-mysql-async

**Comment by HalCroves** [comment]
Ah oui, ne cherche pas plus loin.

Dans le sujet, à un moment, il été dit que pour Linux, il fallait utiliser la branche 2.x pour des problèmes de compatibilités. (je ne retrouve pas le post, car depuis le temps, l'auteur a mis à jour les informations...)

:D

**Comment by CubeTroy** [comment]
Ah d'accord, bon bah merci pour ton aide 
Et bonne continuations ( PS: la nouvelle update besoins de la télécharger ou pas ?)

**Comment by HalCroves** [comment]
Prend juste le fichier client/**client.lua** : https://raw.githubusercontent.com/HalCroves/gcphone/master/gcphone/client/client.lua

J'ai pas pu tester celui que j'ai update, donc je suis retourné en arrière.

Je clôture ce ticket.

Merci pour ton retour rapide. :+1:

**Comment by CubeTroy** [comment]
Tous fonctionne à 100% !
