### ISSUE TITLE
Ouvrir le téléphone dans le coma

### ISSUE THREAD

**Issue by CubeTroy** [HalCroves/gcphone#3]
Hey ! 
C''est encore moi =)
Voila donc je voulais savoir si tu pouvais changer pour que quand nous sommes dans le coma avec esx_ambulancejob qu'on pourrait ouvrir le téléphone pour justement appeler l'ambulance!
Merci

**Comment by HalCroves** [comment]
Hello, 

Pourquoi ne pas utiliser le "_**send distress signal**_" via la touche **G** ?

- Envoi un message aux ambulanciers
- Envoi les coordonnées aux ambulanciers

Du coup pas besoin d'ouvrir le téléphone en étant dans le coma (qui pour moi n'a aucun sens, car non faisable IRL)

---
For use distress signal (esx_ambulancejob), you need to edit the client.main : 

Replace :

```lua
function SendDistressSignal()
	local playerPed = PlayerPedId()
	local coords	= GetEntityCoords(playerPed)

	ESX.ShowNotification(_U('distress_sent'))
	TriggerServerEvent('esx_phone:send', 'ambulance', _U('distress_message'), false, {
		x = coords.x,
		y = coords.y,
		z = coords.z
	})
end
```
By this :

```lua
function SendDistressSignal()
	local playerPed = PlayerPedId()
	PedPosition		= GetEntityCoords(playerPed)
	
	local PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z }

	ESX.ShowNotification(_U('distress_sent'))

    TriggerServerEvent('esx_addons_gcphone:startCall', 'ambulance', _U('distress_message'), PlayerCoords, {

		PlayerCoords = { x = PedPosition.x, y = PedPosition.y, z = PedPosition.z },
	})
end
```

Au cas ou, n'oublie pas de citer tes sources. Parce que bon, sur FiveMFrance :-1:  ...(https://fivem-france.net/viewtopic.php?p=10199#p10199)

**Comment by CubeTroy** [comment]
La source sur FiveMFrance elle y et puisque j'ai donner le lien pour télécharger ton gcphone

**Comment by HalCroves** [comment]
C'est surtout la phrase "**J'ai trouvé comment résoudre le soucis du Whitescreen !"** qui me gêne.

Tu aurais peut être pu remplacer ta phrase par ""**J'ai trouvé comment résoudre le soucis du Whitescreen , grâce à la solution trouvé sur ce github https://github.com/HalCroves/gcphone/ "**. 

C'est juste une question de formulation. Je suis assez tatillon sur ça ^_^

Mais bon passons.

La solution apporté pour les appels ambulances te convient-elle ? Elle a été testé et fonctionne plutôt bien.
Pour tester tu peux te setjobs ambulance et ensuite tu utilises le /die. En appuyant sur G, tu devrais recevoir le sms :+1:

**Comment by CubeTroy** [comment]
Sa fonctionne reste plus qu'a traduire !
Merci encore ( ps: je change la publication fivemfrance)

**Comment by HalCroves** [comment]
@CubeTroy, merci pour la modif.
Il faudra surement changer la position du distress signal également. Il me semble qu'elle n'est pas super lisible.

Je ferme le ticket.
