### ISSUE TITLE
Taxi 

### ISSUE THREAD

**Issue by CubeTroy** [HalCroves/gcphone#5]
Hey
Pas moyen d'ajouter l'appelle taxi même si on peut le faire nous même, sa serais cool !
Merci

**Comment by HalCroves** [comment]
Hello,
Ajouter l'appel taxi ? Tu peut être un peu plus explicite, j'ai pas compris ta demande :)

**Comment by CubeTroy** [comment]
Et bien dans les messages favoris sur le téléphone tu as police ambulance
mécano etc  il faudrait mettre taxi par défaut

**Comment by HalCroves** [comment]
Hello o7
C'est fait.

- V.mysql-async 2.0 : https://github.com/HalCroves/gcphone/commit/6da8603e1293b0822d4b7ed6d8d4bdd17b8e5509
- V.mysql-async 3.0 : https://github.com/HalCroves/gcphone/commit/d1bc411093bff79c1a938da8e052449820dacc4b
