### ISSUE TITLE
New update not working for me. 

### ISSUE THREAD

**Issue by Malviaa** [HalCroves/gcphone#6]
https://imgur.com/EoL4ecV
I can't open the phone. Anyone know why this is happening?

**Comment by HalCroves** [comment]
Hi,
The last mysql syntax is not really good. I will rollback files :)

**Comment by HalCroves** [comment]
Download this files : 

- https://github.com/HalCroves/gcphone/blob/mysql-async-3.x/gcphone/server/app_tchat.lua
- https://github.com/HalCroves/gcphone/blob/mysql-async-3.x/gcphone/server/server.lua

**Comment by Malviaa** [comment]
Wow thanks for the quick answer ;D

**Comment by Malviaa** [comment]
> Hi,
> The last mysql syntax is not really good. I will rollback files :)

for some reason I still can't open the phone. Every time I try to open the phone "F2" the character just does the animation and the phone doesn't show.  And the same error occur https://imgur.com/EoL4ecV
Any ideas?

**Comment by HalCroves** [comment]
Humm it's complicated.. I'm at work. I think the config.json file has a problem...
Clear cache for test.
Otherwise I'll try to see tonight

**Comment by Malviaa** [comment]
I-

> Humm it's complicated.. I'm at work. I think the config.json file has a problem...
> Clear cache for test.
> Otherwise I'll try to see tonight

I tried using another config.json file without success. I clear cache every time I install something new

**Comment by HalCroves** [comment]
I'm so sorry, I can not do anything for the moment :(

**Comment by Malviaa** [comment]
> I'm so sorry, I can not do anything for the moment :(

It's alright, take your time. I have no clue how to fix this hehe ^^

**Comment by HalCroves** [comment]
Ok, i have upload the good files. The gcphone on version mysql-async 3.0 works perfectly
- https://github.com/HalCroves/gcphone/tree/mysql-async-3.x

There was an error in the config.json

- https://github.com/HalCroves/gcphone/commit/fcce13fb8bfd54fd107be3196bd5f4ffee90143a
